<?php

namespace SV\FullMessageTextPermission\XF\Service\Post;

class Notifier extends XFCP_Notifier
{
	public function notify($timeLimit = null)
	{
		return parent::notify($timeLimit); // TODO: Change the autogenerated stub
	}

}